#
#
#

all :
	make -C FPEmu
	make -C FAsm
	make -C HWDesign
	make -C FDisassem
	make -C CF_Forth
	make -C CF_Forth_V2
	make -C AF_Forth

clean :
	make -C FPEmu clean
	make -C FAsm clean
	make -C HWDesign clean
	make -C CF_Forth clean
	make -C CF_Forth_V2 clean
	make -C AF_Forth clean
	make -C FDisassem clean

# --------------- end of file -----------------------------------------
