all :
	make -C FPEmu
	make -C FAsm
	make -C HWDesign
	make -C CF_Forth

clean :
	make -C FPEmu clean
	make -C FAsm clean
	make -C HWDesign clean
	make -C CF_Forth clean

# --------------- end of file -----------------------------------------
