all :
	make -C FPEmu
	make -C FAsm
	make -C HWDesign

clean :
	make -C FPEmu clean
	make -C FAsm clean
	make -C HWDesign clean

# --------------- end of file -----------------------------------------
